### PR TITLE
Separate out the table building so that external programs can build a…

### PR DESCRIPTION
**Pull request by AngledLuffa**
Separate out the table building so that external programs can build a same-looking table when using the script as a module

### CODE REVIEW

**Review by martinpopel — APPROVED** [review]

**Comment by martinpopel** [comment]
I will merge this tomorrow, if there are no comments from @foxik and @dan-zeman.
Travis fails only on Python 3.2 and 3.3, which seem to be not supported by Travis anymore, so we can ignore Travis.

**Comment by AngledLuffa** [comment]
Thanks, sounds great!

**Comment by foxik** [comment]
I am fine with the changes too :-)

**Comment by AngledLuffa** [comment]
Great, thanks!  Does that mean we can merge this in?

**Comment by foxik** [comment]
Merged, thanks for the patch!

**Pull request merged**
